spring.application.name=grocery

#database

spring.data.mongodb.uri=mongodb://localhost:27017/test
spring.data.mongodb.database=test

#aws s3 bucket

aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.s3.bucketname=grocery-service
jwt.secret.key=mK4vL9nQpRsTuWxYzAbBcDeFgHiJkLoMnOpQrStUvWxYz1234


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#razorpay configuration

razorpay_key=${RAZORPAY_KEY}
razorpay_secret=${RAZORPAY_SECRET}